name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # registry: # optional. If not set then will default to Docker Hub
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Login to Docker Hub
      run: docker login
      
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag web-scraper:latest
      
    - name: Change tag of Docker image
      run: docker tag web-scraper:latest ${{ secrets.DOCKER_USERNAME }}/web-scraper:latest
      
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/web-scraper:latest
