name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: pip install -r requirements.txt &&
              apt-get update &&
              apt-get install -y wkhtmltopdf &&
              export PATH=$PATH:/usr/local/bin/wkhtmltopdf

    - name: Run tests
      run: python src/tests/run_tests.py
    
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # registry: # optional. If not set then will default to Docker Hub
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Login to Docker Hub
      run: docker login
      
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag web-scraper:latest
      
    - name: Change tag of Docker image
      run: docker tag web-scraper:latest ${{ secrets.DOCKER_USERNAME }}/web-scraper:latest
      
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/web-scraper:latest
